name: indian_sports_authority
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.5.1
  sensors_plus: ^4.0.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  camera: ^0.10.0+4
  tflite: ^1.1.2
  

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/videos/demo1.mp4
    - assets\demo2.mp4
    # - assets/videos/demo3.mp4
    # - assets/videos/demo4.mp4
